# Generated by Django 5.2.4 on 2025-08-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jap_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Eng_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Studio', models.CharField(blank=True, max_length=50, null=True)),
                ('Producer', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Anime_Image')),
            ],
        ),
    ]
