# Generated by Django 5.2.4 on 2025-08-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_genre_animedb_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedb',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='animes', to='AdminApp.genre'),
        ),
    ]
