# Generated by Django 5.2.4 on 2025-08-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_animedb_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='Episode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animedb',
            name='genres',
            field=models.ManyToManyField(blank=True, to='AdminApp.genre'),
        ),
    ]
