# Generated by Django 5.2.4 on 2025-08-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_animedb_episode_alter_animedb_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
