# Generated by Django 5.2.4 on 2025-08-14 16:43

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_animedb_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='versions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sub', 'Subbed'), ('dub', 'Dubbed')], max_length=7),
        ),
    ]
