# Generated by Django 5.2.4 on 2025-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_animedb_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('tv', 'TV Series')], default='tv', max_length=10),
        ),
    ]
