# Generated by Django 5.2.4 on 2025-08-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_animedb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedb',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
