# Generated by Django 5.2.4 on 2025-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_alter_animedb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedb',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('tv', 'TV Series')], default='TV Series', max_length=10),
        ),
    ]
