# Generated by Django 5.2.4 on 2025-08-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_alter_animedb_type'),
        ('WebApp', '0002_alter_registrationdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AdminApp.animedb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.registrationdb')),
            ],
        ),
        migrations.CreateModel(
            name='RatingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='AdminApp.animedb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='WebApp.registrationdb')),
            ],
            options={
                'unique_together': {('anime', 'user')},
            },
        ),
    ]
