# Generated by Django 5.2.5 on 2025-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_animedb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedb',
            name='episode_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
