# Generated by Django 5.2.5 on 2025-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_animedb_episode_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedb',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('tv series', 'TV Series')], default='TV Series', max_length=15),
        ),
    ]
