# Generated by Django 5.2.5 on 2025-08-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_animedb_type'),
        ('WebApp', '0002_alter_registrationdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchListDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('watching', 'Watching'), ('on_hold', 'On-Hold'), ('plan_to_watch', 'Plan to Watch'), ('dropped', 'Dropped'), ('completed', 'Completed')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.animedb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.registrationdb')),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
