# Generated by Django 5.2.5 on 2025-08-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_animedb_type'),
        ('WebApp', '0003_watchlistdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistdb',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='AdminApp.animedb'),
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='category',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch')], default='plan_to_watch', max_length=20),
        ),
    ]
