# Generated by Django 5.2.5 on 2025-08-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_animedb_type'),
        ('WebApp', '0004_alter_watchlistdb_anime_alter_watchlistdb_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistdb',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.animedb'),
        ),
        migrations.AlterField(
            model_name='watchlistdb',
            name='category',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On-Hold'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch')], max_length=20),
        ),
    ]
