# Generated by Django 5.2.5 on 2025-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_remove_watchlistdb_added_at_alter_watchlistdb_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistdb',
            name='anime_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='watchlistdb',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
