# Generated by Django 5.2.5 on 2025-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_watchlistdb_anime_name_watchlistdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Image', models.ImageField(blank=True, null=True, upload_to='Profile_Image')),
                ('User_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Current_Pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('New_Pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('Confirm_Pwd', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
