# Generated by Django 5.2.5 on 2025-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_profilepagedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePageDB',
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image'),
        ),
    ]
